name: Upload to Remote Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-to-server:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Build or prepare files to upload
      - name: Build Project (optional)
        run: |
          echo "Building project..."
          mkdir -p output
          echo "Hello, World!" > output/example.txt

      # Upload files to remote server
      - name: Upload to Remote Server
        run: |
          sshpass -p "$SERVER_PASSWORD" scp -p index.html $SERVER_USER@52.149.127.16:/var/www/html
        #sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r output/ $SERVER_USER@52.149.127.16:/var/www/html
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        #run: |
        #  scp -r output/ administrador@20.240.240.229:/var/www/html
        #env:
        #  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Optional: Notify success
      - name: Notify Completion
        run: echo "Files have been uploaded to the remote server successfully!"


